### ISSUE TITLE
Register pre-built css?

### ISSUE THREAD

**Issue by jimpil** [cljfx/css#2]
Hi there,

First of all many thanks for your work on cljfx - great stuff indeed :+1:

Now, I have a small cljfx app, and was wondering if there is an easy way to add dark-mode to it. A bit of googling led me to [this](https://stackoverflow.com/questions/49159286/make-a-dark-mode-with-javafx), and the second answer looks rather nice in the included screenshot (my app has similar-ish components). So basically I'm trying to figure out if there is an easy way to register the already built CSS shown there. My first question is - do I even need `cjfx/css`, or can I somehow pass the css straight to `cljfx/cljfx`? If I do need it, can I simply register that ready CSS (i.e. w/o building a map)?

Many thanks in advance

**Comment by vlaaad** [comment]
Hi! If you already have a CSS file, you don't need cljfx/css at all, you can just specify resource path of that CSS in `:stylesheets` prop of a `:scene`. cljfx/css solves 2 problems:
- expressivity of defining CSS, i.e. you can use Clojure to define styles;
- feedback loop of iterating on CSS — you don't have to restart your app when changing the CSS;

**Comment by skynet-gh** [comment]
There is a use case for allowing raw CSS to be registered to these in-memory URLs too: consider custom user themes in CSS files outside of the classpath (not resources). There may be ways to deal with that, but they all seem very messy.
